// Lists
export const UPDATE_LISTS = "UPDATE_LISTS";
export const UPDATE_ACTIVE_LIST = "UPDATE_ACTIVE_LIST";

// Tasks
export const UPDATE_ACTIVE_TASK = "UPDATE_ACTIVE_TASK";
export const UPDATE_TASK_DATA = "UPDATE_TASK_DATA";
export const CREATE_NEW_TASK = "CREATE_NEW_TASK";
export const DELETE_TASK = "DELETE_TASK";

// Application

// TasksForma
export const UPDATE_TASK_FORM_NAME = "UPDATE_TASK_FORM_NAME";
export const UPDATE_TASK_FORM_DATE = "UPDATE_TASK_FORM_DATE";
export const UPDATE_TASK_FORM_HOUR = "UPDATE_TASK_FORM_HOUR";
export const UPDATE_TASK_FORM_STATUS = "UPDATE_TASK_FORM_STATUS";
